<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\AnimalCategory;
use App\Models\Batch;
use App\Models\BatchType;
use App\Models\Caravan;
use App\Models\CaravanWeight;
use App\Models\Company;
use App\Models\TransferOrder;
use App\Models\TransferOrderDestination;
use Illuminate\Database\Seeder;

/**
 * Animals for the CACT-01 test sheets in `ai-agent/image_test/cact001/`
 * (generated by `ai-agent/scripts/generate_cact01_images.py`).
 *
 *  - CAC-A-01..40: own animals in the Cría batch "Lote Testing Cría (cambio actividad)", each with
 *    a current weight and a dentition, so the sheets can show real growth against a known baseline.
 *    Every third one is a female. Weights run 196..274 kg, dentition DL for the first thirty and
 *    2D for the rest.
 *  - CAC-B-01..04: animals sitting in ANOTHER batch, "Lote Testing Recría (ajeno)", so the invalid
 *    sheet can show NOT_IN_SOURCE_BATCH without inventing a tag.
 *  - Two destination batches that already exist, to exercise the "existing batch" path and the two
 *    management-system warnings at once:
 *      "Recría Testing Declarada"   -> is_confined = true  (declared, so a PASTURA box differs)
 *      "Recría Testing Sin Declarar" -> is_confined = null  (nobody was ever asked)
 *
 * Re-running it puts every animal back in its batch with its baseline weight — CAC-B included,
 * which an order executed from /transfer can carry off — and deletes the batches the sheets
 * create ({@see self::SHEET_CREATED_BATCHES}) once they are empty, so the valid sheets can be
 * loaded again without a migrate:fresh:
 *     php artisan tenants:seed --class=ActivityChangeTestAnimalsSeeder
 */
class ActivityChangeTestAnimalsSeeder extends Seeder
{
    private const SOURCE_BATCH_NAME = 'Lote Testing Cría (cambio actividad)';
    private const FOREIGN_BATCH_NAME = 'Lote Testing Recría (ajeno)';
    private const DECLARED_BATCH_NAME = 'Recría Testing Declarada';
    private const UNDECLARED_BATCH_NAME = 'Recría Testing Sin Declarar';

    private const SOURCE_ANIMALS = 40;
    private const FOREIGN_ANIMALS = 4;
    private const BASELINE_DATE = '2026-06-15';

    /** Written by hand on the sheets as batches to create; never seeded. */
    private const SHEET_CREATED_BATCHES = [
        'Recría Prueba Única 2026',
        'Recría Prueba Sin Pesos 2026',
        'Invernada Prueba Nueva',
        'Cria Prueba Sin Manejo',
    ];

    public function run(): void
    {
        $company = Company::first();

        if (!$company) {
            $this->command?->warn('ActivityChangeTestAnimalsSeeder: no hay compañía cargada. Se omite.');

            return;
        }

        $companyId = (int) $company->id;
        $calfCategoryId = AnimalCategory::withoutGlobalScopes()->where('code', 'TERNERO')->value('id');

        $sourceBatch = $this->resolveBatch($companyId, self::SOURCE_BATCH_NAME, 'CRIA', null, 'Lote propio reservado a pruebas de CACT-01: origen del movimiento.');
        $foreignBatch = $this->resolveBatch($companyId, self::FOREIGN_BATCH_NAME, 'RECRIA', false, 'Lote ajeno al movimiento: sirve para probar NOT_IN_SOURCE_BATCH.');
        $this->resolveBatch($companyId, self::DECLARED_BATCH_NAME, 'RECRIA', true, 'Destino existente con el manejo declarado a corral.');
        $this->resolveBatch($companyId, self::UNDECLARED_BATCH_NAME, 'RECRIA', null, 'Destino existente SIN el manejo declarado: la planilla avisa y no lo completa.');

        for ($n = 1; $n <= self::SOURCE_ANIMALS; $n++) {
            $this->seedAnimal(
                $companyId,
                sprintf('CAC-A-%02d', $n),
                (int) $sourceBatch->id,
                $n % 3 === 0 ? 'H' : 'M',
                $n <= 30 ? 0 : 2,
                196.0 + ($n * 2),
                $calfCategoryId
            );
        }

        for ($n = 1; $n <= self::FOREIGN_ANIMALS; $n++) {
            $this->seedAnimal(
                $companyId,
                sprintf('CAC-B-%02d', $n),
                (int) $foreignBatch->id,
                'M',
                2,
                280.0 + $n,
                $calfCategoryId
            );
        }

        // A sheet loaded without an order creates a REGISTERED one; it would hold the batch it
        // created and the cleanup below could not delete it.
        TransferOrder::withoutGlobalScopes()
            ->where('company_id', $companyId)
            ->where('source_batch_id', $sourceBatch->id)
            ->where('kind', 'REGISTERED')
            ->delete();

        $this->deleteSheetCreatedBatches($companyId);

        $this->command?->info(sprintf(
            'ActivityChangeTestAnimalsSeeder: %d animales (CAC-A-01..%02d) en "%s" y %d ajenos (CAC-B-01..0%d) en "%s".',
            self::SOURCE_ANIMALS,
            self::SOURCE_ANIMALS,
            $sourceBatch->name,
            self::FOREIGN_ANIMALS,
            self::FOREIGN_ANIMALS,
            $foreignBatch->name
        ));
    }

    /**
     * Runs after the animals went back, so a batch a previous load created is empty by now. One
     * that still holds animals or an order is left alone and reported.
     */
    private function deleteSheetCreatedBatches(int $companyId): void
    {
        $created = Batch::withoutGlobalScopes()
            ->where('company_id', $companyId)
            ->whereIn('name', self::SHEET_CREATED_BATCHES)
            ->get();

        foreach ($created as $batch) {
            $held = Caravan::withoutGlobalScopes()->where('batch_id', $batch->id)->exists()
                || TransferOrder::withoutGlobalScopes()->where('source_batch_id', $batch->id)->exists()
                || TransferOrderDestination::withoutGlobalScopes()->where('target_batch_id', $batch->id)->exists();

            if ($held) {
                $this->command?->warn("ActivityChangeTestAnimalsSeeder: el lote '{$batch->name}' tiene animales u órdenes; no se borra.");

                continue;
            }

            $batch->delete();
        }
    }

    private function resolveBatch(int $companyId, string $name, string $activityCode, ?bool $isConfined, string $observaciones): Batch
    {
        $activity = Activity::withoutGlobalScopes()->where('code', $activityCode)->first();
        $operational = BatchType::withoutGlobalScopes()->where('code', 'OPERATIONAL')->first();

        return Batch::withoutGlobalScopes()->updateOrCreate(
            ['company_id' => $companyId, 'name' => $name],
            [
                'farm_id' => null,
                'activity_id' => $activity?->id,
                'batch_type_id' => $operational?->id,
                'is_confined' => $isConfined,
                'is_active' => true,
                'is_system' => false,
                'observaciones' => $observaciones,
            ]
        );
    }

    private function seedAnimal(
        int $companyId,
        string $identification,
        int $batchId,
        string $sex,
        int $teeth,
        float $weight,
        ?int $categoryId
    ): void {
        $caravan = Caravan::withoutGlobalScopes()->updateOrCreate(
            ['company_id' => $companyId, 'identification' => $identification],
            ['batch_id' => $batchId, 'sex' => $sex, 'teeth' => $teeth, 'category_id' => $categoryId]
        );

        // One baseline weight, current. Re-running the seeder rewrites it rather than piling up
        // history, so a sheet loaded twice always measures against the same starting point.
        CaravanWeight::where('caravan_id', $caravan->id)->delete();

        CaravanWeight::create([
            'caravan_id' => $caravan->id,
            'weight' => $weight,
            'current' => true,
            'weighing_date' => self::BASELINE_DATE,
            'notes' => 'Peso base de pruebas CACT-01.',
        ]);
    }
}
