<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\AnimalCategory;
use App\Models\Batch;
use App\Models\BatchType;
use App\Models\Caravan;
use App\Models\CaravanGestation;
use App\Models\CaravanLineage;
use App\Models\Company;
use Illuminate\Database\Seeder;

/**
 * Calves at foot for the DEST-01 test sheets in `ai-agent/image_test/dest001/`
 * (generated by `ai-agent/scripts/generate_dest01_images.py`).
 *
 *  - DST-T-01..46: nursing calves with their mothers DST-V-01..46 in the own breeding batch
 *    "Lote Testing Cría (destete)", born BIRTH_DATE. Every third calf is a female.
 *  - DST-T-47: a calf already weaned into the existing weaning batch "Destete Septiembre 2026",
 *    so the invalid sheet can show ALREADY_WEANED and the "existing batch" destination.
 *
 * Re-running it puts DST-T-01..46 back at foot in the breeding batch, so the valid sheets can be
 * loaded again without a migrate:fresh:
 *     php artisan tenants:seed --class=WeaningTestCalvesSeeder
 */
class WeaningTestCalvesSeeder extends Seeder
{
    private const BREEDING_BATCH_NAME = 'Lote Testing Cría (destete)';
    private const WEANING_BATCH_NAME = 'Destete Septiembre 2026';
    private const NURSING_CALVES = 46;
    private const WEANED_CALF = 47;
    private const BIRTH_DATE = '2026-02-10';
    private const SERVICE_START_DATE = '2025-05-05';

    public function run(): void
    {
        $company = Company::first();

        if (!$company) {
            $this->command?->warn('WeaningTestCalvesSeeder: no hay compañía cargada. Se omite.');

            return;
        }

        $companyId = (int) $company->id;
        $cowCategoryId = AnimalCategory::withoutGlobalScopes()->where('code', 'VACA')->value('id');
        $calfCategoryId = AnimalCategory::withoutGlobalScopes()->where('code', 'TERNERO')->value('id');

        $breedingBatch = $this->resolveBreedingBatch($companyId);
        $weaningBatch = $this->resolveWeaningBatch($companyId);

        for ($n = 1; $n <= self::WEANED_CALF; $n++) {
            $weaned = $n === self::WEANED_CALF;
            $this->seedCalfAtFoot(
                $companyId,
                $n,
                (int) $breedingBatch->id,
                $weaned ? (int) $weaningBatch->id : (int) $breedingBatch->id,
                !$weaned,
                $cowCategoryId,
                $calfCategoryId
            );
        }

        $this->command?->info(sprintf(
            'WeaningTestCalvesSeeder: %d crías al pie (DST-T-01..%02d) en "%s" y DST-T-%02d destetada en "%s".',
            self::NURSING_CALVES,
            self::NURSING_CALVES,
            $breedingBatch->name,
            self::WEANED_CALF,
            $weaningBatch->name
        ));
    }

    private function resolveBreedingBatch(int $companyId): Batch
    {
        $criaActivity = Activity::withoutGlobalScopes()->where('code', 'CRIA')->first()
            ?? Activity::create(['code' => 'CRIA', 'name' => 'Cría']);

        return Batch::withoutGlobalScopes()->updateOrCreate(
            ['company_id' => $companyId, 'name' => self::BREEDING_BATCH_NAME],
            [
                'farm_id' => null,
                'activity_id' => $criaActivity->id,
                'is_active' => true,
                'is_system' => false,
                'observaciones' => 'Lote propio reservado a pruebas de DEST-01: vacas con cría al pie.',
            ]
        );
    }

    private function resolveWeaningBatch(int $companyId): Batch
    {
        $criaActivity = Activity::withoutGlobalScopes()->where('code', 'CRIA')->first();
        $weaningType = BatchType::withoutGlobalScopes()->where('code', 'WEANING')->first();

        return Batch::withoutGlobalScopes()->updateOrCreate(
            ['company_id' => $companyId, 'name' => self::WEANING_BATCH_NAME],
            [
                'farm_id' => null,
                'activity_id' => $criaActivity?->id,
                'batch_type_id' => $weaningType?->id,
                'is_active' => true,
                'is_system' => false,
                'observaciones' => 'Lote de destete existente para pruebas de DEST-01.',
            ]
        );
    }

    private function seedCalfAtFoot(
        int $companyId,
        int $n,
        int $motherBatchId,
        int $calfBatchId,
        bool $nursing,
        ?int $cowCategoryId,
        ?int $calfCategoryId
    ): void {
        $number = str_pad((string) $n, 2, '0', STR_PAD_LEFT);

        $mother = Caravan::withoutGlobalScopes()->updateOrCreate(
            ['company_id' => $companyId, 'identification' => "DST-V-{$number}"],
            ['batch_id' => $motherBatchId, 'sex' => 'H', 'category_id' => $cowCategoryId, 'teeth' => 6]
        );

        $gestation = CaravanGestation::withoutGlobalScopes()->updateOrCreate(
            ['caravan_id' => $mother->id, 'end_date' => self::BIRTH_DATE],
            ['start_date' => self::SERVICE_START_DATE, 'is_current' => false, 'success' => true]
        );

        $calf = Caravan::withoutGlobalScopes()->updateOrCreate(
            ['company_id' => $companyId, 'identification' => "DST-T-{$number}"],
            ['batch_id' => $calfBatchId, 'sex' => $n % 3 === 0 ? 'H' : 'M', 'category_id' => $calfCategoryId]
        );

        CaravanLineage::updateOrCreate(
            ['caravan_id' => $calf->id],
            [
                'mother_id' => $mother->id,
                'gestation_id' => $gestation->id,
                'birth_date' => self::BIRTH_DATE,
                'is_nursing' => $nursing,
            ]
        );
    }
}
